import Container from "./_component/container/Container";
import Header from "./_component/header/Header";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Container>
          <Header />
        </Container>

        {children}
      </body>
    </html>
  );
}
